### ISSUE TITLE
无法加载 DLL“WebView2Loader.dll”: 找不到指定的模块。

### ISSUE THREAD

**Issue by xuzhe521** [Awoodwhale/Goose_Goose_Duck_Hack_Py#1]
![image](https://user-images.githubusercontent.com/35841999/213703595-288a90f3-80af-436c-9a3f-a433b62b9885.png)

**Comment by Awoodwhale** [comment]
> ![image](https://user-images.githubusercontent.com/35841999/213703595-288a90f3-80af-436c-9a3f-a433b62b9885.png)

win几的系统，有edge吗？我这里的GUI是靠浏览器内核启动的，win10默认应该是edge来启动

**Comment by Awoodwhale** [comment]
我在edge的github上看到了这两个issue，你可以参考一下：[#2046](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2046)和[#1236](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1236)

其中提到了可能是中文路径的问题，或者是浏览器版本较低，建议升级

**Comment by xuzhe521** [comment]
> > ![image](https://user-images.githubusercontent.com/35841999/213703595-288a90f3-80af-436c-9a3f-a433b62b9885.png)
> 
> win几的系统，有edge吗？我这里的GUI是靠浏览器内核启动的，win10默认应该是edge来启动


好的  我看一下  谢谢

**Comment by T5ive** [comment]
I got this problem with py3.11
solution by use python version 3.10 or lower

**Comment by Awoodwhale** [comment]
> 

yes, this program is used python3.8 to build up
