### ISSUE TITLE
You are not local player! 报错

### ISSUE THREAD

**Issue by 11055** [Awoodwhale/Goose_Goose_Duck_Hack_Py#2]
终端管理员执行   python.exe .\main.py 成功识别到鹅鸭杀
<pymem.Pymem object at 0x0000021E6C6A7610>
[2023/01/31 07:16:15 AM] Find module <GameAssembly.dll>
[2023/01/31 07:16:15 AM] Find module base address <0x7ffac4bf0000>
[2023/01/31 07:16:15 AM] Find module SizeOfImage <0x4486000>
[2023/01/31 07:16:15 AM] Success init game process!

但是功能一个都用不了
报错:
Failed to hack speed. You are not local player!

**Comment by Awoodwhale** [comment]
> 终端管理员执行 python.exe .\main.py 成功识别到鹅鸭杀 <pymem.Pymem object at 0x0000021E6C6A7610> [2023/01/31 07:16:15 AM] Find module <GameAssembly.dll> [2023/01/31 07:16:15 AM] Find module base address <0x7ffac4bf0000> [2023/01/31 07:16:15 AM] Find module SizeOfImage <0x4486000> [2023/01/31 07:16:15 AM] Success init game process!
> 
> 但是功能一个都用不了 报错: Failed to hack speed. You are not local player!

是的，最近鹅鸭杀大更新，很多偏移地址改了，加上修改了内存保护措施，本仓库的代码还没更新- -
